services:
  duklamaps:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Persistentn√≠ data mimo kontejner
      - ./timetableData:/app/timetableData
      - ./logs:/app/logs
    restart: unless-stopped
